#!/bin/sh

sed -E 's/\[T: (.+)-[0-9]+\]/[T: \1]/' | perl -pe 's/(?<time>[^ ]* [^ ]*) \[L: (?<level>[^\]]*)] \[O: (?<object>[^\]]*)] \[I: (?<obj_instance>[^\]]*)] \[U: (?<user>[^\]]*)] \[S: (?<session>[^\]]*)] \[P: (?<platformid>[^\]]*)] \[T: (?<thread>[^\]]*)] (?<message>.*)/[L: $+{level}] [I: $+{obj_instance}] [T: $+{thread}] $+{message}/' | sort | uniq -c | sort -rn | head -n 25
